### ISSUE TITLE
CLI for simple slurm

### ISSUE THREAD

**Issue by rsanchezgarc** [amq92/simple_slurm#12]
Hi,

Thank you very much for this package. It is super useful.

Would it be possible to have a simple command line interface to use simple_slurm? It would be great if I can submit simple commands from the shell directly.
Something like
simple_slurm --command "echo running;hostname" --cpus_per_task 1

Thanks!

**Comment by amq92** [comment]
Good idea, I've included it in release [v0.2.6](https://github.com/amq92/simple_slurm/releases/tag/v0.2.6). See [here](https://github.com/amq92/simple_slurm/tree/master#using-the-command-line) for more details.
