### ISSUE TITLE
Submitting Python functions?

### ISSUE THREAD

**Issue by diningphil** [amq92/simple_slurm#13]
Hi Arturo,

I was wondering if it is possible to submit python functions to slurm with `simple_slurm`. It would be a super nice feature to have.
Do you know if anyone already managed to do that?

Many thanks,
Federico

**Comment by amq92** [comment]
Hi, currently you can do `slurm.sbatch("python my_code.py arg1 arg2")`
Of course you need to have a parser in place for `my_code.py` (such as [argparse](https://docs.python.org/3/library/argparse.html), [click](https://click.palletsprojects.com/en/8.1.x/), [typer](https://typer.tiangolo.com/), etc) to properly run your function from the command line.

**Comment by hunoutl** [comment]
@diningphil  https://github.com/facebookincubator/submitit could be a solution for you
