### ISSUE TITLE
srun option in sbatch ?

### ISSUE THREAD

**Issue by hunoutl** [amq92/simple_slurm#15]
In some contexts, you have to call srun in a sbatch script (multi-node execution).
The workaround I use makes add 'srun' inside run_cmd. 
`slurm.sbatch('srun python train.py')`

Is a srun option in sbatch function could be usefull ?
possible contribution

**Comment by amq92** [comment]
There is already a `slurm.srun(cmd)` command (see [here](https://github.com/amq92/simple_slurm#introduction) and [here](https://github.com/amq92/simple_slurm/blob/8a163388cd4a65a9e8d39347db5cb2e9d6190920/simple_slurm/core.py#L90)) but it serves a different purpose.

From what I can see from the documentation, the `srun` command within the multi-node execution acts like any other command in the `sbatch` script.
Thus, I dont see why or how it would be treated differently (**i.e.,** warranting a custom option)...

Do you have an idea on how would you implement it ?

**Comment by hunoutl** [comment]
Indeed you are right, after thinking about it it is not a good idea to optionally overload the slurm.sbatch().
Taking into account the srun command directly in the command to be submitted allows for easier reading during. 
In the opposite case (with this 'decomposition'), we would move away from the way so I write my sbatch scripts usually ...
