### ISSUE TITLE
Version 0.2.1 got uploaded to pypi without *.txt files included.

### ISSUE THREAD

**Issue by alexandervaneck** [amq92/simple_slurm#8]
Hi @amq92 👋 Nice to meet you.
Thank you for maintaining/creating simple-slurm, I've been thoroughly enjoying using it.

I noticed that when installing simple-slurm==0.2.1 that the *.txt files are not included in the package, and thus simple-slurm doesn't work with the latest version. I wasn't able to spot quickly what is wrong with the setup.py.

In case you were already aware of this, my apologies 🙇 .

Once again, thank you for your work.

Alexander

**Comment by AlexanderVanEck** [comment]
And now I also noticed that we can't downgrade to simple-slurm==0.1.7 anymore b/c it's been removed from pypi. 🤔
